### PR TITLE
added docker file and kubernetes file

### LINKED ISSUE #128: [New Feature]: Dockerize the app
### 🎮 feature Request

I want to tell you that we have to dockerize the app because when in future anyone want to clone our app and use our app in different operating system then our project dont run in their system so for removing this problem we have to dockerize the app so that everyone can easily use our app

### Point down the features

when someone clone or run app in different operating system then he simply use
when someone use different version of package in own system then it create virtual environment and use this app
in future when this version in corrupted then someone want to use this app then user can use
after dockerize the app you can also publish image on dockerhub

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by agarwalhimanshugaya**
## PR Description 📜

I write the docker file and kubernetes file and also comment out the command needed for running this app through this you can run app locally and also deploy locally
Fixes #128 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by agarwalhimanshugaya** [comment]
please review my pr

**Comment by agarwalhimanshugaya** [comment]
@Mukesh751 kindly assign the label else it is not counted in gssoc

**Comment by agarwalhimanshugaya** [comment]
@sanjay-kv sr kindly add label sr otherwise it is not added into gssoc

**Comment by Mukesh751** [comment]
@agarwalhimanshugaya done

**Pull request merged**
