### PR TITLE
Ui_enhancement_and_introduction

### PR DESCRIPTION
**Pull request by tishubohra**
## PR Description 📜
I have added some css to enhance it's look. Apart from that alerts are given to the player once he completes the level,  as it's necessary for the the player to know at what level he is.
Fixes # <1>

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by tishubohra** [comment]
Ui_enhancement is done and also, alerts are added for better interaction

**Comment by Mukesh751** [comment]
could you please share the screenshots of changes you made

**Comment by tishubohra** [comment]
> could you please share the screenshots of changes you made

Here it is, 
3-D effect is not visible in the picture but background hve 3-D effect. [

](url)

https://github.com/GameSphere-MultiPlayer/Squard-line/assets/97802942/14eb9c83-0f62-4179-91d6-f1d5ff59b72c

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
